window.BICst = window.BICst || {};
BICst.REPORT_SERVER_PARAM = {
    SPLIT_PAGE_PREVIEW_SETTING: 1,
    FORM_PAGE_SETTING: 2,
    DATA_ANALYSIS_SETTING: 3,
    IMPORT_CSS: 4,
    IMPORT_JS: 5,
    ERROR_TEMPLATE_DEFINE: 6,
    PRINT_SETTING: 7
};
BICst.REPORT_TEMPLATE_WEB_SETTING = {
    BASE: 1,
    PRINT: 2,
    SPLIT_PAGE_PREVIEW_SETTING: 3,
    FORM_PAGE_SETTING: 4,
    DATA_ANALYSIS_SETTING: 5,
    BROWSER: 6,
    IMPORT_CSS: 7,
    IMPORT_JS: 8
};

BICst.REPORT_TEMPLATE_WEB_SETTING_TOOLS = {
    FIRST_PAGE: 1,
    PRE_PAGE: 2,
    NEXT_PAGE: 3,
    LAST_PAGE: 4,
    PRINT: 5,
    EXPORT: 6,
    EMAIL: 7
};